import { InsertMoroccanProduct } from "../../shared/models/moroccan_products";

export const moroccanProductsData: InsertMoroccanProduct[] = [
  // ── CENTRALE LAITIÈRE / JAOUDA ──────────────────────────────────────────
  {
    barcode: "6111245101014",
    name: "Lait Jaouda Entier UHT 1L",
    brand: "Centrale Laitière",
    category: "Lait",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Lait entier UHT",
    nutriments: { sugars: 4.8, fat: 3.5, proteins: 3.2, salt: 0.1, saturated_fat: 2.1, fiber: 0, energy_kcal: 64 },
    calories: 64,
  },
  {
    barcode: "6111245101021",
    name: "Lait Jaouda Demi-écrémé UHT 1L",
    brand: "Centrale Laitière",
    category: "Lait",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Lait demi-écrémé UHT",
    nutriments: { sugars: 4.8, fat: 1.5, proteins: 3.4, salt: 0.1, saturated_fat: 1.0, fiber: 0, energy_kcal: 46 },
    calories: 46,
  },
  {
    barcode: "6111245102011",
    name: "Beurre Jaouda Doux 250g",
    brand: "Centrale Laitière",
    category: "Beurre",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Crème pasteurisée (lait)",
    nutriments: { sugars: 0.5, fat: 82, proteins: 0.7, salt: 0.05, saturated_fat: 55, fiber: 0, energy_kcal: 745 },
    calories: 745,
  },
  {
    barcode: "6111245103018",
    name: "Crème Fraîche Jaouda 250ml",
    brand: "Centrale Laitière",
    category: "Crème",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Crème fraîche pasteurisée (lait)",
    nutriments: { sugars: 3.0, fat: 30, proteins: 2.5, salt: 0.05, saturated_fat: 20, fiber: 0, energy_kcal: 300 },
    calories: 300,
  },
  {
    barcode: "6111245104015",
    name: "Fromage Fondu Jaouda 8 portions",
    brand: "Centrale Laitière",
    category: "Fromage",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Fromages (lait), eau, beurre, sel, correcteur d'acidité: E331",
    nutriments: { sugars: 1.5, fat: 22, proteins: 10, salt: 1.4, saturated_fat: 14, fiber: 0, energy_kcal: 245 },
    calories: 245,
  },

  // ── YAWMI ───────────────────────────────────────────────────────────────
  {
    barcode: "6111005101010",
    name: "Yawmi Yaourt Brassé Nature 125g",
    brand: "Centrale Laitière",
    category: "Yaourt",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Lait entier pasteurisé, ferments lactiques",
    nutriments: { sugars: 5.0, fat: 3.2, proteins: 3.5, salt: 0.12, saturated_fat: 2.1, fiber: 0, energy_kcal: 62 },
    calories: 62,
  },
  {
    barcode: "6111005102017",
    name: "Yawmi K'ssoul Vanille 125g",
    brand: "Centrale Laitière",
    category: "Yaourt",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Lait entier, sucre, amidon modifié, arôme vanille, ferments lactiques",
    nutriments: { sugars: 14, fat: 2.8, proteins: 3.2, salt: 0.1, saturated_fat: 1.8, fiber: 0, energy_kcal: 93 },
    calories: 93,
  },
  {
    barcode: "6111005103014",
    name: "Yawmi Yaourt Fruits Rouges 125g",
    brand: "Centrale Laitière",
    category: "Yaourt",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Lait entier, préparation aux fruits rouges (sucre, fruits), ferments lactiques",
    nutriments: { sugars: 15, fat: 2.5, proteins: 3.0, salt: 0.1, saturated_fat: 1.6, fiber: 0.3, energy_kcal: 97 },
    calories: 97,
  },

  // ── KOUTOUBIA ───────────────────────────────────────────────────────────
  {
    barcode: "6111073101012",
    name: "Merguez de Bœuf Koutoubia 400g",
    brand: "Koutoubia",
    category: "Viandes transformées",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Bœuf halal 70%, eau, fécule de pomme de terre, épices, sel, ail, piment, boyau de mouton",
    nutriments: { sugars: 0.5, fat: 18, proteins: 14, salt: 1.8, saturated_fat: 6, fiber: 0, energy_kcal: 218 },
    calories: 218,
  },
  {
    barcode: "6111073102019",
    name: "Saucisses de Poulet Koutoubia 400g",
    brand: "Koutoubia",
    category: "Viandes transformées",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Poulet halal 75%, eau, amidon, sel, épices, boyau comestible",
    nutriments: { sugars: 0.8, fat: 14, proteins: 16, salt: 1.5, saturated_fat: 4, fiber: 0, energy_kcal: 190 },
    calories: 190,
  },
  {
    barcode: "6111073103016",
    name: "Escalopes de Dinde Koutoubia 500g",
    brand: "Koutoubia",
    category: "Viandes",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Dinde halal 100%",
    nutriments: { sugars: 0, fat: 4, proteins: 22, salt: 0.1, saturated_fat: 1, fiber: 0, energy_kcal: 120 },
    calories: 120,
  },
  {
    barcode: "6111073104013",
    name: "Nuggets de Poulet Koutoubia 400g",
    brand: "Koutoubia",
    category: "Viandes transformées",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Poulet halal 60%, chapelure, farine de blé, eau, sel, épices, huile de tournesol",
    nutriments: { sugars: 2, fat: 16, proteins: 18, salt: 1.2, saturated_fat: 3, fiber: 0.5, energy_kcal: 220 },
    calories: 220,
  },
  {
    barcode: "6111073201018",
    name: "Kefta de Bœuf Koutoubia 400g",
    brand: "Koutoubia",
    category: "Viandes transformées",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Bœuf halal 90%, oignons, persil, épices marocaines (cumin, paprika, sel)",
    nutriments: { sugars: 1, fat: 20, proteins: 18, salt: 1.0, saturated_fat: 7, fiber: 0.3, energy_kcal: 255 },
    calories: 255,
  },

  // ── BIMO ────────────────────────────────────────────────────────────────
  {
    barcode: "6111108101013",
    name: "Mikado Choco Bimo 150g",
    brand: "Bimo",
    category: "Biscuits",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Farine de blé, sucre, chocolat au lait 25%, beurre, œufs, sel, arôme vanille",
    nutriments: { sugars: 28, fat: 22, proteins: 7, salt: 0.4, saturated_fat: 10, fiber: 1.5, energy_kcal: 490 },
    calories: 490,
  },
  {
    barcode: "6111108102010",
    name: "Crackers Bimo Salés 100g",
    brand: "Bimo",
    category: "Biscuits salés",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Farine de blé, huile végétale, sel, levure, malt d'orge",
    nutriments: { sugars: 2, fat: 15, proteins: 9, salt: 1.5, saturated_fat: 3, fiber: 2, energy_kcal: 440 },
    calories: 440,
  },
  {
    barcode: "6111108103017",
    name: "Biscuits Bimo Avoine et Miel 200g",
    brand: "Bimo",
    category: "Biscuits",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Flocons d'avoine, farine de blé, miel, sucre, huile végétale, sel",
    nutriments: { sugars: 20, fat: 12, proteins: 6, salt: 0.3, saturated_fat: 4, fiber: 3, energy_kcal: 415 },
    calories: 415,
  },

  // ── TRIA (Pâtes) ────────────────────────────────────────────────────────
  {
    barcode: "6111022101014",
    name: "Vermicelles Tria 500g",
    brand: "Tria",
    category: "Pâtes",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Semoule de blé dur, eau",
    nutriments: { sugars: 2.5, fat: 1.5, proteins: 12, salt: 0.01, saturated_fat: 0.3, fiber: 3, energy_kcal: 350 },
    calories: 350,
  },
  {
    barcode: "6111022102011",
    name: "Coudes Tria 500g",
    brand: "Tria",
    category: "Pâtes",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Semoule de blé dur, eau",
    nutriments: { sugars: 2.5, fat: 1.5, proteins: 12, salt: 0.01, saturated_fat: 0.3, fiber: 3, energy_kcal: 350 },
    calories: 350,
  },
  {
    barcode: "6111022103018",
    name: "Spaghetti Tria 500g",
    brand: "Tria",
    category: "Pâtes",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Semoule de blé dur, eau",
    nutriments: { sugars: 2.5, fat: 1.5, proteins: 12, salt: 0.01, saturated_fat: 0.3, fiber: 3, energy_kcal: 350 },
    calories: 350,
  },
  {
    barcode: "6111022201013",
    name: "Langues d'Oiseau Tria 500g",
    brand: "Tria",
    category: "Pâtes",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Semoule de blé dur, eau",
    nutriments: { sugars: 2.5, fat: 1.5, proteins: 12, salt: 0.01, saturated_fat: 0.3, fiber: 3, energy_kcal: 350 },
    calories: 350,
  },

  // ── LESIEUR CRISTAL ─────────────────────────────────────────────────────
  {
    barcode: "6111009101013",
    name: "Huile de Tournesol Cristal 1L",
    brand: "Lesieur Cristal",
    category: "Huiles",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Huile de tournesol raffinée",
    nutriments: { sugars: 0, fat: 100, proteins: 0, salt: 0, saturated_fat: 12, fiber: 0, energy_kcal: 900 },
    calories: 900,
  },
  {
    barcode: "6111009102010",
    name: "Huile d'Olive Extra Vierge Cristal 0.5L",
    brand: "Lesieur Cristal",
    category: "Huiles",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Huile d'olive extra vierge",
    nutriments: { sugars: 0, fat: 100, proteins: 0, salt: 0, saturated_fat: 14, fiber: 0, energy_kcal: 900 },
    calories: 900,
  },
  {
    barcode: "6111009103017",
    name: "Margarine Fleurial 500g",
    brand: "Lesieur Cristal",
    category: "Corps gras",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Huiles végétales (palme, tournesol), eau, sel, émulsifiants (E471, E322), arôme, colorant (E160a), vitamines A et D",
    nutriments: { sugars: 0.5, fat: 75, proteins: 0.2, salt: 0.8, saturated_fat: 25, fiber: 0, energy_kcal: 675 },
    calories: 675,
  },

  // ── AÏCHA (Conserves) ───────────────────────────────────────────────────
  {
    barcode: "6111044101015",
    name: "Concentré de Tomate Aïcha 70g",
    brand: "Aicha",
    category: "Conserves",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Tomates fraîches concentrées, sel",
    nutriments: { sugars: 8, fat: 0.5, proteins: 4, salt: 1.2, saturated_fat: 0.1, fiber: 2, energy_kcal: 58 },
    calories: 58,
  },
  {
    barcode: "6111044102012",
    name: "Concentré de Tomate Aïcha 135g",
    brand: "Aicha",
    category: "Conserves",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Tomates fraîches concentrées, sel",
    nutriments: { sugars: 8, fat: 0.5, proteins: 4, salt: 1.2, saturated_fat: 0.1, fiber: 2, energy_kcal: 58 },
    calories: 58,
  },
  {
    barcode: "6111044103019",
    name: "Harissa Aïcha 135g",
    brand: "Aicha",
    category: "Condiments",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Piments rouges, huile d'olive, ail, sel, coriandre, carvi",
    nutriments: { sugars: 3, fat: 8, proteins: 2, salt: 2.5, saturated_fat: 1, fiber: 4, energy_kcal: 95 },
    calories: 95,
  },
  {
    barcode: "6111044104016",
    name: "Confiture d'Abricot Aïcha 400g",
    brand: "Aicha",
    category: "Confitures",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Abricots 45%, sucre, jus de citron, gélifiant: pectine",
    nutriments: { sugars: 55, fat: 0.1, proteins: 0.5, salt: 0.02, saturated_fat: 0, fiber: 1, energy_kcal: 230 },
    calories: 230,
  },
  {
    barcode: "6111044105013",
    name: "Confiture de Fraise Aïcha 400g",
    brand: "Aicha",
    category: "Confitures",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Fraises 45%, sucre, jus de citron, gélifiant: pectine",
    nutriments: { sugars: 55, fat: 0.1, proteins: 0.5, salt: 0.02, saturated_fat: 0, fiber: 1, energy_kcal: 230 },
    calories: 230,
  },
  {
    barcode: "6111044201014",
    name: "Sardines Aïcha à l'Huile 125g",
    brand: "Aicha",
    category: "Conserves poissons",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Sardines, huile de tournesol, sel",
    nutriments: { sugars: 0, fat: 14, proteins: 22, salt: 1.3, saturated_fat: 3, fiber: 0, energy_kcal: 215 },
    calories: 215,
  },

  // ── AGROS / DARI (Couscous & céréales) ──────────────────────────────────
  {
    barcode: "6111016101016",
    name: "Couscous Moyen Agros 1kg",
    brand: "Agros",
    category: "Céréales",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Semoule de blé dur, eau",
    nutriments: { sugars: 2, fat: 0.8, proteins: 12, salt: 0.01, saturated_fat: 0.1, fiber: 2.5, energy_kcal: 355 },
    calories: 355,
  },
  {
    barcode: "6111016102013",
    name: "Couscous Fin Agros 1kg",
    brand: "Agros",
    category: "Céréales",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Semoule de blé dur, eau",
    nutriments: { sugars: 2, fat: 0.8, proteins: 12, salt: 0.01, saturated_fat: 0.1, fiber: 2.5, energy_kcal: 355 },
    calories: 355,
  },
  {
    barcode: "6111016103010",
    name: "Couscous Gros Agros 1kg",
    brand: "Agros",
    category: "Céréales",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Semoule de blé dur, eau",
    nutriments: { sugars: 2, fat: 0.8, proteins: 12, salt: 0.01, saturated_fat: 0.1, fiber: 2.5, energy_kcal: 355 },
    calories: 355,
  },

  // ── CHLEF (Farine & Semoule) ─────────────────────────────────────────────
  {
    barcode: "6111054101012",
    name: "Farine de Blé Tendre Chlef 1kg",
    brand: "Chlef",
    category: "Farines",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Farine de blé tendre",
    nutriments: { sugars: 2, fat: 1.2, proteins: 10, salt: 0.01, saturated_fat: 0.2, fiber: 3, energy_kcal: 338 },
    calories: 338,
  },
  {
    barcode: "6111054102019",
    name: "Semoule Fine Chlef 1kg",
    brand: "Chlef",
    category: "Semoules",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Semoule de blé dur",
    nutriments: { sugars: 2.5, fat: 1, proteins: 13, salt: 0.01, saturated_fat: 0.2, fiber: 2.8, energy_kcal: 355 },
    calories: 355,
  },

  // ── OULMÈS / EAUX MINÉRALES ──────────────────────────────────────────────
  {
    barcode: "6111020101015",
    name: "Eau Minérale Oulmès Gazeuse 1.5L",
    brand: "Oulmès",
    category: "Eaux",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Eau minérale naturelle gazeuse",
    nutriments: { sugars: 0, fat: 0, proteins: 0, salt: 0, saturated_fat: 0, fiber: 0, energy_kcal: 0 },
    calories: 0,
  },
  {
    barcode: "6111020102012",
    name: "Sidi Ali Eau Minérale 1.5L",
    brand: "Sidi Ali",
    category: "Eaux",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Eau minérale naturelle",
    nutriments: { sugars: 0, fat: 0, proteins: 0, salt: 0, saturated_fat: 0, fiber: 0, energy_kcal: 0 },
    calories: 0,
  },
  {
    barcode: "6111020103019",
    name: "Ain Saiss Eau Minérale 1.5L",
    brand: "Ain Saiss",
    category: "Eaux",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Eau minérale naturelle",
    nutriments: { sugars: 0, fat: 0, proteins: 0, salt: 0, saturated_fat: 0, fiber: 0, energy_kcal: 0 },
    calories: 0,
  },
  {
    barcode: "6111020104016",
    name: "Ain Ifrane Eau de Source 1.5L",
    brand: "Ain Ifrane",
    category: "Eaux",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Eau de source naturelle",
    nutriments: { sugars: 0, fat: 0, proteins: 0, salt: 0, saturated_fat: 0, fiber: 0, energy_kcal: 0 },
    calories: 0,
  },

  // ── DOHA (Sardines & Huile Olive) ────────────────────────────────────────
  {
    barcode: "6111003101019",
    name: "Huile d'Olive Doha 0.75L",
    brand: "Doha",
    category: "Huiles",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Huile d'olive",
    nutriments: { sugars: 0, fat: 100, proteins: 0, salt: 0, saturated_fat: 14, fiber: 0, energy_kcal: 900 },
    calories: 900,
  },
  {
    barcode: "6111055101010",
    name: "Sardines Doha à l'Huile 125g",
    brand: "Doha",
    category: "Conserves poissons",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Sardines 75%, huile de tournesol, sel",
    nutriments: { sugars: 0, fat: 14, proteins: 22, salt: 1.3, saturated_fat: 3, fiber: 0, energy_kcal: 215 },
    calories: 215,
  },
  {
    barcode: "6111055102017",
    name: "Thon Doha à l'Huile 160g",
    brand: "Doha",
    category: "Conserves poissons",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Thon 70%, huile de tournesol, sel",
    nutriments: { sugars: 0, fat: 12, proteins: 27, salt: 1.0, saturated_fat: 2, fiber: 0, energy_kcal: 220 },
    calories: 220,
  },

  // ── CENTRALE SUCRE ───────────────────────────────────────────────────────
  {
    barcode: "6111060101011",
    name: "Sucre Blanc Raffiné Centrale 1kg",
    brand: "Centrale Sucrière",
    category: "Sucres",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Sucre de betterave raffiné",
    nutriments: { sugars: 100, fat: 0, proteins: 0, salt: 0, saturated_fat: 0, fiber: 0, energy_kcal: 400 },
    calories: 400,
  },

  // ── OLIVES ───────────────────────────────────────────────────────────────
  {
    barcode: "6111015101018",
    name: "Olives Vertes Cassées Marinées 350g",
    brand: "Salami",
    category: "Olives",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Olives vertes, eau, sel, ail, citron confit, épices",
    nutriments: { sugars: 0.5, fat: 15, proteins: 1, salt: 3.5, saturated_fat: 2, fiber: 3, energy_kcal: 145 },
    calories: 145,
  },
  {
    barcode: "6111015102015",
    name: "Olives Noires à l'Huile 350g",
    brand: "Salami",
    category: "Olives",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Olives noires, eau, sel, huile d'olive",
    nutriments: { sugars: 0.3, fat: 18, proteins: 1, salt: 2.8, saturated_fat: 2.5, fiber: 3.5, energy_kcal: 168 },
    calories: 168,
  },

  // ── ÉPICES DOHA ──────────────────────────────────────────────────────────
  {
    barcode: "6111025101015",
    name: "Ras El Hanout Doha 100g",
    brand: "Doha",
    category: "Épices",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Mélange d'épices : cumin, coriandre, gingembre, curcuma, cannelle, poivre noir, paprika, cardamome, girofle",
    nutriments: { sugars: 3, fat: 5, proteins: 10, salt: 0.5, saturated_fat: 0.5, fiber: 30, energy_kcal: 280 },
    calories: 280,
  },
  {
    barcode: "6111025102012",
    name: "Cumin Moulu Doha 100g",
    brand: "Doha",
    category: "Épices",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Cumin moulu",
    nutriments: { sugars: 2, fat: 22, proteins: 18, salt: 0.2, saturated_fat: 1, fiber: 10, energy_kcal: 375 },
    calories: 375,
  },

  // ── MIEL ─────────────────────────────────────────────────────────────────
  {
    barcode: "6111035201012",
    name: "Miel d'Eucalyptus Afra 500g",
    brand: "Afra",
    category: "Miel",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Miel pur d'eucalyptus",
    nutriments: { sugars: 82, fat: 0, proteins: 0.3, salt: 0.01, saturated_fat: 0, fiber: 0.2, energy_kcal: 320 },
    calories: 320,
  },
  {
    barcode: "6111035202019",
    name: "Miel de Thym Atlas 250g",
    brand: "Atlas",
    category: "Miel",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Miel naturel de fleurs de thym",
    nutriments: { sugars: 82, fat: 0, proteins: 0.3, salt: 0.01, saturated_fat: 0, fiber: 0.2, energy_kcal: 320 },
    calories: 320,
  },

  // ── HUILE D'ARGAN ────────────────────────────────────────────────────────
  {
    barcode: "6111030101013",
    name: "Huile d'Argan Alimentaire 100ml",
    brand: "Atlas",
    category: "Huiles",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Huile d'argan pure (Argania Spinosa L.)",
    nutriments: { sugars: 0, fat: 100, proteins: 0, salt: 0, saturated_fat: 20, fiber: 0, energy_kcal: 900 },
    calories: 900,
  },

  // ── HALIB / BOISSONS LAITIÈRES ───────────────────────────────────────────
  {
    barcode: "6111245301012",
    name: "Halib Chocolat Centrale 200ml",
    brand: "Centrale Laitière",
    category: "Boissons lactées",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Lait entier, sucre, cacao en poudre 3%, arôme vanille",
    nutriments: { sugars: 12, fat: 3.5, proteins: 3.2, salt: 0.12, saturated_fat: 2.3, fiber: 0.3, energy_kcal: 92 },
    calories: 92,
  },

  // ── FROMAGE KIRI MAROC ───────────────────────────────────────────────────
  {
    barcode: "6111035301011",
    name: "Kiri Fromage à Tartiner 8 Portions",
    brand: "Centrale Laitière",
    category: "Fromage",
    isHalal: true,
    isHalalCertified: true,
    ingredients: "Fromages (lait de vache), protéines de lait, crème, eau, sel, épaississants (E407, E415)",
    nutriments: { sugars: 3, fat: 25, proteins: 10, salt: 1.0, saturated_fat: 17, fiber: 0, energy_kcal: 280 },
    calories: 280,
  },

  // ── CHOCOLAT POULAIN ─────────────────────────────────────────────────────
  {
    barcode: "6111108301011",
    name: "Chocolat au Lait Poulain 100g",
    brand: "Poulain",
    category: "Chocolats",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Sucre, beurre de cacao, lait en poudre, cacao, émulsifiant: lécithine de soja, arôme vanille",
    nutriments: { sugars: 54, fat: 30, proteins: 7, salt: 0.2, saturated_fat: 18, fiber: 2, energy_kcal: 530 },
    calories: 530,
  },

  // ── CAFÉ ─────────────────────────────────────────────────────────────────
  {
    barcode: "6111095101015",
    name: "Café Moulu Tradition 250g",
    brand: "Cafés du Maroc",
    category: "Café",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Café arabica et robusta moulu",
    nutriments: { sugars: 0, fat: 0, proteins: 0, salt: 0, saturated_fat: 0, fiber: 0, energy_kcal: 2 },
    calories: 2,
  },

  // ── BISCOTTES / PAIN ─────────────────────────────────────────────────────
  {
    barcode: "6111108401010",
    name: "Biscottes Complètes Bimo 300g",
    brand: "Bimo",
    category: "Biscottes",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Farine de blé complet 65%, eau, huile de tournesol, sucre, sel, levure",
    nutriments: { sugars: 8, fat: 7, proteins: 12, salt: 0.8, saturated_fat: 1, fiber: 7, energy_kcal: 380 },
    calories: 380,
  },

  // ── RIZ ──────────────────────────────────────────────────────────────────
  {
    barcode: "6111076101013",
    name: "Riz Basmati Dari 1kg",
    brand: "Dari",
    category: "Riz",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Riz basmati",
    nutriments: { sugars: 1, fat: 0.5, proteins: 7, salt: 0.01, saturated_fat: 0.1, fiber: 1, energy_kcal: 350 },
    calories: 350,
  },

  // ── LÉGUMES SECS ─────────────────────────────────────────────────────────
  {
    barcode: "6111076201012",
    name: "Lentilles Dari 1kg",
    brand: "Dari",
    category: "Légumineuses",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Lentilles",
    nutriments: { sugars: 2, fat: 1, proteins: 25, salt: 0.01, saturated_fat: 0.1, fiber: 11, energy_kcal: 340 },
    calories: 340,
  },
  {
    barcode: "6111076202019",
    name: "Pois Chiches Dari 1kg",
    brand: "Dari",
    category: "Légumineuses",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Pois chiches",
    nutriments: { sugars: 3, fat: 6, proteins: 19, salt: 0.01, saturated_fat: 0.6, fiber: 12, energy_kcal: 360 },
    calories: 360,
  },

  // ── SNACKS ───────────────────────────────────────────────────────────────
  {
    barcode: "6111108501019",
    name: "Chips Doritos Nacho Cheese 180g",
    brand: "Bimo",
    category: "Snacks",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Maïs, huile végétale, assaisonnement fromage (poudre de fromage, sel, sucre, épices, arômes)",
    nutriments: { sugars: 3, fat: 28, proteins: 7, salt: 1.5, saturated_fat: 4, fiber: 3, energy_kcal: 500 },
    calories: 500,
  },

  // ── THÉ ──────────────────────────────────────────────────────────────────
  {
    barcode: "6111080201016",
    name: "Thé Vert Menthe Sahel 100g",
    brand: "Sahel",
    category: "Thés & Infusions",
    isHalal: true,
    isHalalCertified: false,
    ingredients: "Thé vert, menthe poivrée séchée",
    nutriments: { sugars: 0, fat: 0, proteins: 0.5, salt: 0, saturated_fat: 0, fiber: 0, energy_kcal: 5 },
    calories: 5,
  },
];
